#!/bin/bash




### TO DO LIST
# 
# install sencha
# configure emacs
# add js
# check to see if submodules need to be updated/synced
# offer to create GOPATH if not found


# Default colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLACK='\033[0;30m'


CUR_USER=`who am i | awk '{print $1}'`

# Clean this up at somepoint since this is kind of redundant now
CUR_GO_PATH=`env | grep GOPATH 2> /dev/null | cut -d "=" -f2`


# Prints the help menu
usage() {
    cat <<EOF
setup_dev_system

NAME
        setup_dev_system - Configures a new install to conform to FBNC's development needs

SYNOPSIS
        setup_dev_system <flag>

DESCRIPTION
        This tool both checks system status and installs the needed toosl for
        development. The primary things that can be installed with this tool
        include the EPEL repo, core dev utilities, Cassandra (2.2.3), 
        Cassandra's dependencies, Git (2.8.0), Golang's developer toolset, and 
        ExtJS. Additionally this sets up the Go dev directory, generates your 
        Github ssh keys, creates Git aliases, pulls down Novetta's core repos 
        (Common, kerbproxy, etc.) and otherwise tries to provide a consistent
        development environment.

        -h
               prints this help screen

        -c
               checks the system

        -i       
               installs and configures everything

AUTHOR
        Another handy tool by James Stoup (jstoup@novetta.com)        
EOF
    
    exit 1
}


checkForBin() {
    if hash $1 2>/dev/null; then
	BIN_VERSION=`$1 $2 | head -1`
        printf "  [SUCCESS] - $1 ($BIN_VERSION)\n"
    else
        printf "  [FAILURE] - $1 not found!\n"
    fi
}


# Checks the status of the system
checkStatus() {
    echo "----------------------------"
    echo "-  CHECKING SYSTEM STATUS  -"
    echo "----------------------------"
    echo ""


    ### Make sure this is run properly
    if [ "$EUID" -eq 0 ]; then
	echo "please DON'T run me with sudo"
	exit 1
    fi

    ### Check if sudo is setup for this user
    echo "> Checking permissions"
    sudo echo -n " "
    if [ $? -ne 0 ]; then
	printf "  [FAILURE] - sudo\n"
	echo "    Sudo is not setup for this user!"
        echo "    To enable sudo for user $USER run visudo and"
	echo "    add this line at the end of the file:"
        echo "    <your_user_name_here> ALL=(ALL) NOPASSWD: ALL"
    else
	printf " [SUCCESS] - sudo enabled for this user\n"
    fi
    
    echo ""
    

    ### Check environment variables
    echo "> Checking for environment variables"

    CLS=`env | grep _CLUSTER 2> /dev/null`
    CAS=`env | grep CASSANDRA_CONSISTENCY 2> /dev/null`
    MY_GOPATH=`env | grep GOPATH 2> /dev/null`
    MY_GOBIN=`env | grep GOBIN 2> /dev/null`

    if [[ -z $CLS ]] ; then
	printf "  [FAILURE] - "
    else
	printf "  [SUCCESS] - "
    fi
    echo "*_CLUSTER"

    if [[ -z $CAS ]] ; then
	printf "  [FAILURE] - "
    else
	printf "  [SUCCESS] - "
    fi
    echo "CASSANDRA_CONSISTENCY"


    if [[ -z $MY_GOPATH ]] ; then
	printf "  [FAILURE] - "
	echo "WARNING the GOPATH environment variable is not set. Please fix this and run this check again!"
	exit 1
    else
	printf "  [SUCCESS] - "
    fi
    echo "GOPATH"

    if [[ -z $MY_GOBIN ]] ; then
	printf "  [FAILURE] - "
    else
	printf "  [SUCCESS] - "
    fi
    echo "GOBIN"

    if [[ -z $CAS ]] || [[ -z $CLS ]]; then
	echo "To set the needed variables for this session"
	echo "source the .env file in the conf directory"
	echo "of the application you are trying to run."
    fi
    echo ""


    ### Check if the required directories exists in /opt
    echo "> Checking /opt directories"    

    OPT_FILES_STR=`find $CUR_GO_PATH/src/github.com/Novetta -name "*.env" | xargs grep "/opt/" | cut -d ":" -f2 | grep -v "^#" | grep export | cut -d "=" -f2 | cut -d "/" -f3 | tr -d "\"" | sort -u  | tr "\n" " " | tr " " "\n" | grep -v PATH | tr "\n" " "`

    OIFS=$IFS
    IFS=" "
    OPT_FILES=($OPT_FILES_STR)

    for key in "${!OPT_FILES[@]}" 
    do 
	KEY_DIR="/opt/${OPT_FILES[$key]}"

	# Check if dir exists
	if [ -d $KEY_DIR ]; then
	    KEY_PERM=`stat -c "%a" $KEY_DIR`
	    
	    # If it exists, make sure the permissions are correct
	    if [ $KEY_PERM -ne 755 ] ; then
		printf "  [FAILURE] - $KEY_DIR (permissions should be 755 not $KEY_PERM)\n"
	    else
		printf "  [SUCCESS] - $KEY_DIR\n"
	    fi
	else
	    printf "  [FAILURE] - $KEY_DIR\n"
	fi

    done

    IFS=$OIFS

    echo ""


    ### Make sure migrate is installed
    echo "> Checking for required tools"

    checkForBin migrate "-version"
    checkForBin cassandra "-v"
    checkForBin go "version"
    checkForBin git "--version"
    checkForBin emacs "--version"
    checkForBin vim "--version"
    checkForBin sencha "help"


    ### Check the Git submodules for each project
    # Need to run 'git submodule status --recursive' at the root of each project
    # output a warning if it starts with "-" (not initialized)
    # output a failure if it starts with a "+" or a "U" (hash doesn't match or conflicts)
    # git submodule init --recursive
    # git submodule update --recursive
    # git submodule sync --recursive  should do it


    echo ""
    exit 1
}



# Does all the heavy lifting of installing stuff
installAndConfigure() {
    clear
    counter=1

    #####################################################
    ### Check to make sure this isn't run with sudo
    #####################################################
    if [ $EUID -eq 0 ]; then
	echo "This script doesn't need to be run with sudo"
	exit 1
    fi


    #####################################################
    ### Check to make sure we aren't running this as root
    #####################################################
    WHO_AM_I=`who am i | awk '{print $1}'`
    if [[ "$WHO_AM_I" = "root" ]]; then
	echo "WARNING! You can't run this AS the root user!" 
	echo "This should be installed as a user because this script"
	echo "installs into the user's home directory and you do not "
	echo "this installed in /root."
	exit 1
    fi


    #####################################################
    ### Welcome
    #####################################################
    echo "=================================================="
    echo "===     DEVELOPER SETUP/CONFIGURE SCRIPT      ==="
    echo "=================================================="
    echo ""
    echo "Welcome to the developers setup script. This"
    echo "script should configure a new machine for our"
    echo "basic development layout."
    echo ""

    echo ""
    echo "--SYSTEM"

    #####################################################
    ### Add some repos
    #####################################################
    read -p "  [$counter] Do you want to install extra repos? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing the extra repos"
	echo "  ==================================="

	sudo yum install -y epel-release
	sudo yum install -y epel-release.noarch
	echo ""
    fi
    echo ""


    #####################################################
     ### Add some RPMS
    #####################################################
    read -p "  [$counter] Do you want to install extra RPMS? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing extra RPMs"
	echo "  ==================================="

	RPMS=(
	    emacs
	    curl-devel
	    expat-devel
	    gettext-devel
	    openssl-devel
	    zlib-devel
	    gcc
	    perl-ExtUtils-MakeMaker
	    xclip
	    ack
	    zeromq
	    zeromq-devel
	    autoconf
	    automake
	    cmake
	    freetype-devel
	    gcc-c++
	    git
	    libtool
	    make
	    mercurial
	    nasm
	    yasm
	    pkgconfig
	    zlib-devel
	    ftp
	)

	for rpm in "${RPMS[@]}"
	do
	    echo "--------------------------"
	    echo "> INSTALLING RPM $rpm"
	    sudo yum install -y $rpm
	done

	echo ""
    fi
    echo ""   


    echo ""   
    echo "--DATABASE"

    #####################################################
    ### Install Cassandra
    #####################################################
    read -p "  [$counter] Do you want to install Cassandra 2.2.3? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing Cassandra 2.2.3"
	echo "  ==================================="

	EXCLUDE_STR="exclude=cassandra22-2.2.4* dsc22-2.2.4* cassandra22-tools-2.2.4* cassandra22-2.2.5* dsc22-2.2.5* cassandra22-tools-2.2.5*" 
	#sudo echo $EXCLUDE_STR >> /etc/yum.conf
	sudo yum install -y cassandra22.noarch cassandra22-tools.noarch
	echo ""
    fi
    echo ""


    #####################################################
    ### Install Lucene
    #####################################################
        read -p "  [$counter] Do you want to install Lucene? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing Lucene"
	echo "  ==================================="

	NOVAHOME=$GOPATH/src/github.com/Novetta
	LUCENE_PATH=$NOVAHOME/common/lucene/cassandra-lucene-index-plugin* 
	if [ ! -f $LUCENE_PATH ] ; then
	    echo "WARNING! Lucene not found. Check in $GOPATH/common/lucene for the jar file"
	else
	    sudo cp $NOVAHOME/common/lucene/cassandra-lucene-index-plugin* /usr/share/cassandra/lib/
	    sudo chown cassandra:cassandra /usr/share/cassandra/lib/cassandra-lucene-index-plugin*
	    sudo systemctl enable cassandra
	fi
    fi
    echo ""


    #####################################################
    ### Install the migrate tool
    #####################################################
    read -p "  [$counter] Do you want to install the migrate tool? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing Migrate"
	echo "  ==================================="

	go get -u github.com/mattes/migrate

    fi
    echo ""



    echo ""   
    echo "--GOLANG"

    #####################################################
    ### Install Go
    #####################################################
    read -p "  [$counter] Do you want to install Go? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing Go"
	echo "  ==================================="

	# Setup the Go Dev directory structure
	DEV_DIR_NAME="dev"
	mkdir ~/$DEV_DIR_NAME
	cd  ~/$DEV_DIR_NAME
	mkdir bin pkg src
	echo "# Go Environment Variables" >> ~/.bashrc
	echo "export GOPATH=$HOME/$DEV_DIR_NAME" >> ~/.bashrc
	echo "export GOBIN=$GOPATH/bin" >> ~/.bashrc
	echo "export GOROOT=/usr/local/go" >> ~/.bashrc
	echo "" >> ~/.bashrc
	echo "export PATH=$PATH:$GOBIN" >> ~/.bashrc

	cd $HOME/Downloads
	GOVER=1.6.1
	wget "https://storage.googleapis.com/golang/go$GOVER.linux-amd64.tar.gz"
	sudo tar -C /usr/local -xzf go$GOVER.linux-amd64.tar.gz
	echo "export GOPATH=$GOPATH" | tee -a $HOME/.env
	source $HOME/.env
	cd $HOME

    fi
    echo ""


    #####################################################
    ### Install Go Linters
    #####################################################
    read -p "  [$counter] Do you want to install Go Lint? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing Go Lint"
	echo "  ==================================="

	# TODO - put a check in to make sure GOPATH is set
	go get -u github.com/golang/lint/golint

    fi
    echo ""


    #####################################################
    ### Pull down go tools
    #####################################################
    read -p "  [$counter] Do you want to install extra Go tools? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Pulling down the Golang Tools"
	echo "  ==================================="

	cd ~/$DEV_DIR_NAME
	go get golang.org/x/tools/cmd/...
	cd $MY_CUR_DIR
    fi
    echo ""


    echo ""   
    echo "--GIT"

    #####################################################
    ### Install Git
    #####################################################
    read -p "  [$counter] Do you want to install Git 2.8.0? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing Git"
	echo "  ==================================="

	sudo yum install -y curl-devel expat-devel gettext-devel openssl-devel zlib-devel gcc perl-devel
	sudo yum install -y asciidoc xmlto docbook2X
	sudo ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
	sudo yum install -y autoconf
	GIT_VERSION_TO_INSTALL="2.8.0"
	MY_CUR_DIR=`pwd`
	cd ~/Downloads
	wget https://github.com/git/git/archive/v$GIT_VERSION_TO_INSTALL.tar.gz
	tar -xzf v$GIT_VERSION_TO_INSTALL.tar.gz
	cd git-$GIT_VERSION_TO_INSTALL
	make configure
	./configure --prefix=/usr
	make all doc info
	sudo make install install-doc install-html install-info
	cd ../
	rm -rf git-$GIT_VERSION_TO_INSTALL*
	rm -rf v$GIT_VERSION_TO_INSTALL.tar.gz
	cd $MY_CUR_DIR

    fi
    echo ""


    #####################################################
    ### Configure Git
    #####################################################
    read -p "  [$counter] Do you want to configure Git? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Setup Git Config"
	echo "  ==================================="

	
	if [[ -z $USER_EMAIL ]] ; then
	    echo -n "Please enter your email address > "
	    read USER_EMAIL

	    while true; do
		echo "You entered: $USER_EMAIL"
		read -p "  [$counter] Is this correct? (y/n) " yn
		case $yn in
 
		    [Yy]* ) break;;
		    [Nn]* ) echo -n "Please enter your email address > " ; read USER_EMAIL;;
		    * ) echo "Please answer yes or no.";;
		esac
	    done
	fi

	git config --global user.name $USER_NAME
	git config --global user.email $USER_EMAIL
	git config --global core.editor emacs
	git config --global core.autocrlf input
	git config --global core.safecrlf true
	git config --global core.excludesfile "~/.gitignore_global"
	git config --global color.ui always
	git config --global push.default simple
	git config --global credential.helper "cache --timeout=36000"
	git config --global url.ssh://git@github.com/.insteadOf https://github.com/
	git config --global alias.co checkout
	git config --global alias.stage add
	git config --global alias.switch checkout
	git config --global alias.unstage "reset HEAD"
	git config --global alias.delete "branch -d"
	GIT_LL_STR='log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --numstat'
	echo "        ll       = $GIT_LL_STR" >> ~/.gitconfig
	GIT_LS_STR='log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate'
	echo "        ls       = $GIT_LS_STR" >> ~/.gitconfig
	GIT_LDR_STR='log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=relative'
	echo "        ldr      = $GIT_LDR_STR" >> ~/.gitconfig
	GIT_LDS_STR='log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=short'
	echo "        lds      = $GIT_LDS_STR" >> ~/.gitconfig

	echo "New data written to ~/.gitconfig"
    fi
    echo ""


    #####################################################
    ### Add your ssh key to github
    #####################################################
    read -p "  [$counter] Do you want to generate your SSH keys for github? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Generating an SSH Key for Github"
	echo "  ==================================="

	echo ""
	echo -n "Please enter your email address > "
	read USER_EMAIL

	while true; do
	    echo "You entered: $USER_EMAIL"
	    read -p "  Is this correct? (y/n) " yn
	    case $yn in
 
		[Yy]* ) break;;
		[Nn]* ) echo -n "Please enter your email address > " ; read USER_EMAIL;;
		* ) echo "Please answer yes or no.";;
	    esac
	done

	ssh-keygen -t rsa -b 4096 -C $USER_EMAIL
	eval $(ssh-agent -s)
	ssh-add ~/.ssh/id_rsa

	echo "Be sure to visit https://github.com/settings/ssh to enter this ssh key."
	echo "Failure to add this key to github will prevent git from working properly."

    fi
    echo ""


    echo ""   
    echo "--NOVETTA"

    #####################################################
    ### Pull down the Novetta repos
    #####################################################
    read -p "  [$counter] Do you want to install the Novetta repos? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Pulling down the Novetta Repos"
	echo "  ==================================="
	echo ""
	echo "This might take a while..."

	NOVA_REPOS=(VideoEnterprise
	    pwcop
	    namegen
	    SSE
	    goldap
	    GoSearchService
	    gmf
	    perseus
	    aide
	    gokerb
	    gocql
	    kerbproxy
	    asn1)

	cd ~/$DEV_DIR_NAME
	
	export GOPATH=$CUR_GO_PATH

	for repo in "${NOVA_REPOS[@]}"
	do
	    echo "--------------------------"
	    echo "> INSTALLING REPO $repo"
	    go get github.com/Novetta/$repo
	    cd $GOPATH/src/github.com/Novetta/$repo
	    echo "> UPDATING REPO"
	    go get -u -f -v 
	    echo "> UPDATING SUBMODULES"
	    git submodule update --init --recursive 
	    cd ../

	done

    fi
    echo ""




    #####################################################
    ### Create app directories in /opt
    #####################################################
    read -p "  [$counter] Do you want to create the app directories in /opt and set correct permissions? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Creating directories in /opt"
	echo "  ==================================="

    OPT_FILES_STR=`find $CUR_GO_PATH/src/github.com/Novetta -name "*.env" | xargs grep "/opt/" | cut -d ":" -f2 | grep -v "^#" | grep export | cut -d "=" -f2 | cut -d "/" -f3 | tr -d "\"" | sort -u  | tr "\n" " " | tr " " "\n" | grep -v PATH | tr "\n" " "`

    OIFS=$IFS
    IFS=" "
    OPT_FILES=($OPT_FILES_STR)

    for key in "${!OPT_FILES[@]}" 
    do 
	KEY_DIR="/opt/${OPT_FILES[$key]}"

	# Check if dir exists
	if [ -d $KEY_DIR ]; then
	    KEY_PERM=`stat -c "%a" $KEY_DIR`
	    
	    # If it exists, make sure the permissions are correct
	    if [ $KEY_PERM -ne 755 ] ; then
		sudo chmod 755 $KEY_DIR
	    fi
	else
	    sudo mkdir -m 755 $KEY_DIR
	fi

	#val="SUCCESS"
	#printf "%10s -[ %30s]\n" "$KEY_DIR" "$val"
	printf "[SUCCESS] %20s\n" "$KEY_DIR"
    done

    IFS=$OIFS

    fi
    echo ""


    echo ""   
    echo "--JAVASCRIPT"


    #####################################################
    ### Install NodeJS & JS Tools
    #####################################################
    read -p "  [$counter] Do you want to install JS tools? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing JS tools & linters"
	echo "  ==================================="

	NODE_GLOBAL="jshint
js-beautify
eslint"

	for N in $NODE_GLOBAL
	do
	    which $N >/dev/null 2>&1 && continue
	    
	    #weird problem pulling in this dependency
	    [ "$N" == "jshint" ] && sudo npm install -g inherits
	    
	    sudo npm install -g $N
	done
    fi
    echo ""




    echo ""   
    echo "--TOOLS"


    #####################################################
    ### Install Chrome
    #####################################################
    read -p "  [$counter] Do you want to install Chrome? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing Chrome"
	echo "  ==================================="

	echo "Installing Google Chrome"
	cd $HOME/Downloads
	wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
	sudo yum install -y google-chrome-stable_current_x86_64.rpm
	cd $HOME
    fi
    echo ""


    #####################################################
    ### Install Emacs    
    #####################################################
    read -p "  [$counter] Do you want to install emacs? (y/n) " -n 1 -r
    counter=$((counter+1)) 

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
	echo ""
	echo "  ==================================="
	echo "  === Installing emacs"
	echo "  ==================================="

	if [ ! -d ~/Downloads ] ; then
	    mkdir ~/Downloads
	fi
	cd ~/Downloads
	emacsVersion=24.5
	wget ftp://ftp.gnu.org/pub/gnu/emacs/emacs-$emacsVersion.tar.gz
	tar -xzf emacs-$emacsVersion.tar.gz
	cd emacs-$emacsVersion
	./configure
	make
	sudo make install
	# put in check to see if emacs was installed correctly
	cd ../
	rm -rf emacs-$emacsVersion

    fi
    echo ""


    # #####################################################
    # ### Install Git Hooks
    # #####################################################
    #     read -p "  [$counter] Do you want to install git hooks? (y/n) " -n 1 -r
    # counter=$((counter+1)) 

    # if [[ $REPLY =~ ^[Yy]$ ]] ; then
    # 	echo ""
    # 	echo "  ==================================="
    # 	echo "  === Installing Git Hooks"
    # 	echo "  ==================================="

    # 	NOVAHOME=$GOPATH/src/github.com/Novetta
    # 	LUCENE_PATH=$NOVAHOME/common/lucene/cassandra-lucene-index-plugin* 
    # 	if [ ! -f $LUCENE_PATH ] ; then
    # 	    echo "WARNING! Lucene not found. Check in $GOPATH/common/lucene for the jar file"
    # 	else
    # 	    sudo cp $NOVAHOME/common/lucene/cassandra-lucene-index-plugin* /usr/share/cassandra/lib/
    # 	    sudo chown cassandra:cassandra /usr/share/cassandra/lib/cassandra-lucene-index-plugin*
    # 	    sudo systemctl enable cassandra
    # 	fi
    # fi
    # echo ""


    #####################################################
    ### Enhance the bash prompt
    #####################################################
    #     read -p "Do you want to enhance the bash prompt? (y/n) " -n 1 -r
    #     if [[ $REPLY =~ ^[Yy]$ ]] ; then
    # 	echo ""
    # 	echo "==================================="
    # 	echo "=== Enhancing bash for git usage"
    # 	echo "==================================="

    # 	NEW_PS1=$(cat <<EOF
    # function _git_prompt() {
    #     local git_status="`git status -unormal 2>&1`"
    #     if ! [[ "$git_status" =~ Not\ a\ git\ repo ]]; then
    #         if [[ "$git_status" =~ nothing\ to\ commit ]]; then
    #             local ansi=42
    #         elif [[ "$git_status" =~ nothing\ added\ to\ commit\ but\ untracked\ files\ present ]]; then
    #             local ansi=43
    #         else
    #             local ansi=41
    #         fi
    #         if [[ "$git_status" =~ On\ branch\ ([^[:space:]]+) ]]; then
    #             branch=${BASH_REMATCH[1]}
    #             test "$branch" != master || branch=' '
    #         else
    #             # Detached HEAD.  (branch=HEAD is a faster alternative.)
    #             branch="(`git describe --all --contains --abbrev=4 HEAD 2> /dev/null ||
    #                 echo HEAD`)"
    #         fi
    #         echo -n '\[\e[0;37;'"$ansi"';1m\]'"$branch"'\[\e[0m\] '
    #     fi
    # }

    # function _prompt_command() {
    #     PS1="`_git_prompt`"'[\u \t \[\033[0;34m\]\w\[\033[0;30m\]]\$\[\e[0m\] '
    # }
    # PROMPT_COMMAND=_prompt_command

    # EOF
    # )
    # 	echo "" >> ~/.bashrc
    # 	echo "#######################################################" >> ~/.bashrc
    # 	echo "# New Git Enhanced Bash Prompt" >> ~/.bashrc
    # 	echo "$NEW_PS1" >> ~/.bashrc
    # 	echo "#######################################################" >> ~/.bashrc
    #     fi
    #     echo ""

    # #---Sencha---#
    # echo "Login and Download Chrome UNTIL DOWNLOAD IS COMPLETED!!!!"
    # google-chrome https://support.sencha.com/#download
    # cd $HOME/Downloads
    # unzip ext*.zip
    # extdir=`ls -d */ | grep ext`
    # echo "Copying Files to $NOVAHOME/ext......."
    # cp -p -r $HOME/Downloads/$extdir $NOVAHOME/ext

    # echo "Installing Sencha CMD"
    # cd $HOME/Downloads
    # wget http://cdn.sencha.com/cmd/6.1.2/no-jre/SenchaCmd-$CMDVER-linux-amd64.sh.zip
    # unzip SenchaCmd-$CMDVER-linux-amd64.sh.zip
    # chmod +x SenchaCmd-$CMDVER*
    # ./SenchaCmd-$CMDVER*
    # echo "export PATH=$PATH:/home/cole/bin/Sencha/Cmd" | tee -a $HOME/.env
    # source $HOME/.env
    # cd $HOME


    #####################################################
    ### Install JS/ExtJS
    #####################################################


    




    echo ""
    exit 1
}





# If they just ran it blind, print the help
if [[ -z "$1" ]]; then
    usage
fi

# Parse the args
while getopts ":hci" opt; do
    case $opt in
	h)
	    usage
	    ;;
	c)
	    check=true
	    checkStatus
	    ;;
	i)
	    install=true
	    installAndConfigure
	    ;;
	*)
	    usage
	    ;;
    esac
done

# Check to make sure they didn't enter gibberish
if [ "$check" = true ] || [ "$install" = true ] ; then
    echo ""
else
    usage
fi



